apiVersion: v1
kind: ConfigMap
metadata:
  name: hellok8s-config
  namespace: realwork
data:
  MESSAGE: "It works with a ConfigMap!"

---

apiVersion: v1
kind: Service
metadata:
  name: hellok8s-svc
  namespace: realwork
spec:
  selector:
    app: hellok8s
  ports:
  - port: 8080
    targetPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellok8s
  namespace: realwork
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hellok8s
  template:
    metadata:
      labels:
        app: hellok8s
    spec:
      containers:
      - image: dchiniquy/kube-node:v4
        name: hellok8s-container
        envFrom:
          - configMapRef:
              name: hellok8s-config